apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-policies
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: policies
  project: acm-policies
  source:
    path: "POLICIES_PATH"
    repoURL: "POLICIES_REPO_URL"
    targetRevision: "POLICIES_REVISION"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
