---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-cluster-acm
  namespace: openshift-gitops
spec:
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /spec/channel
        - /spec/installPlanApproval
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/hub-cluster-acm
    repoURL: ""
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - preserveResourcesOnDeletion=true
    automated:
      prune: true
      selfHeal: true
