apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-cluster-acm
  namespace: openshift-gitops
spec:
  source:
    repoURL: "HUB_CLUSTER_BOOTSTRAP_REPO_URL"
    targetRevision: ""
    kustomize:
      patches:
        - target:
            kind: MultiClusterHub
            name: multiclusterhub
            namespace: open-cluster-management
          patch: |-
            - op: add
              path: /spec/localClusterName
              value: HUB_CLUSTER_NAME
 
