apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/openshift-gitops/argocd-applications/

patches:
  - path: hub-cluster-acm-kustomize-patches.yaml
    target:
      kind: Application
      name: hub-cluster-acm
      namespace: openshift-gitops
