apiVersion: v1
kind: Secret
metadata:
  name: gitops-base-repo-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: 
  password: ADOTOKEN
  username: ADOUSER
---
apiVersion: v1
kind: Secret
metadata:
  name: policies-repo-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: 
  password: ADOTOKEN
  username: ADOUSER
