apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/hub-cluster-acm

patches:
  - path: multiclusterhub-patches.yaml
    target:
      kind: MultiClusterHub
      name: multiclusterhub
      namespace: open-cluster-management