apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-cluster-acm
  namespace: openshift-gitops
spec:
  source:
    repoURL: "https://github.com/SDBrett/acm-hub-cluster-bootstrap"
    targetRevision: main
    path: overlays/test-hub/hub-cluster-acm
