apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-cluster-acm
  namespace: openshift-gitops
spec:
  source:
    repoURL: "https://github.com/SDBrett/acm-hub-cluster-bootstrap"
    targetRevision: main
    kustomize:
      patches:
        - target:
            kind: MultiClusterHub
            name: multiclusterhub
            namespace: open-cluster-management
          patch: |-
            - op: add
              path: /spec/localClusterName
              value: test-hub
            - op: add
              path: /spec/availabilityConfig
              value: Basic
            - op: replace
              path: /spec/overrides/components
              value:
                - name: app-lifecycle
                  enabled: false
                  configOverrides: {}
                - name: cluster-backup
                  enabled: false
                  configOverrides: {}
                - name: cluster-lifecycle
                  enabled: false
                  configOverrides: {}
                - name: cluster-permission
                  enabled: false
                  configOverrides: {}
                - name: cnv-mtv-integrations
                  enabled: false
                  configOverrides: {}
                - name: console
                  enabled: true
                  configOverrides: {}
                - name: fine-grained-rbac
                  enabled: false
                  configOverrides: {}
                - name: grc
                  enabled: true
                  configOverrides: {}
                - name: insights
                  enabled: false
                  configOverrides: {}
                - name: multicluster-engine
                  enabled: true
                  configOverrides: {}
                - name: multicluster-observability
                  enabled: false
                  configOverrides: {}
                - name: search
                  enabled: false
                  configOverrides: {}
                - name: siteconfig
                  enabled: false
                  configOverrides: {}
                - name: submariner-addon
                  enabled: false
                  configOverrides: {}
                - name: volsync
                  enabled: false
                  configOverrides: {}
