apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-cluster-acm
  namespace: openshift-gitops
spec:
  source:
    kustomize:
      patches:
        - target:
            kind: MultiClusterHub
            name: multiclusterhub
            namespace: open-cluster-management
          patch: |-
            - op: add
              path: /spec/localClusterName
              value: hub01
            - op: add
              path: /spec/availabilityConfig
              value: Basic
